const SUPABASE_URL="https://gfwtfxcwcwobduqmywlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable__nYZ3obxkyFO70yPzoVWJg_beIGmf5U";
const supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const $=id=>document.getElementById(id);
const money=n=>"$"+Number(n||0).toFixed(2).replace(".00","");
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
let adminBookings=[];
function calculateEstimate(){const service=$("service").value,start=$("start_time").value,end=$("end_time").value;let total=0;if(service==="Hourly"&&start&&end){const [sh,sm]=start.split(":").map(Number),[eh,em]=end.split(":").map(Number);const hours=(eh*60+em-(sh*60+sm))/60;if(hours>0)total=Math.max(1,hours)*4;}else if(service==="Daily")total=17;else if(service==="Night")total=25;$("estimate").textContent=money(total)}
["service","start_time","end_time"].forEach(id=>$(id).addEventListener("change",calculateEstimate));
const today=new Date().toISOString().split("T")[0];$("start_date").min=today;$("end_date").min=today;$("start_date").addEventListener("change",()=>$("end_date").min=$("start_date").value);
$("bookingForm").addEventListener("submit",async e=>{e.preventDefault();clearError("formError");calculateEstimate();const startDate=$("start_date").value,endDate=$("end_date").value;if(endDate<startDate)return showError("formError","End date cannot be before the start date.");const ref="CS-"+Date.now().toString().slice(-8);const row={booking_reference:ref,service:$("service").value,booking_date:startDate,start_date:startDate,end_date:endDate,start_time:$("start_time").value,end_time:$("end_time").value||null,number_of_children:Number($("number_of_children").value),children_ages:$("children_ages").value.trim(),parent_name:$("parent_name").value.trim(),phone:$("phone").value.trim(),email:$("email").value.trim(),emergency_contact:$("emergency_contact").value.trim(),location:$("location").value.trim(),special_requirements:$("special_requirements").value.trim(),notes:$("notes").value.trim(),estimated_price:Number($("estimate").textContent.replace("$",""))||0,status:"Pending"};const {error}=await supabaseClient.from("bookings").insert(row);if(error){console.error(error);return showError("formError","We could not submit the booking. Please try again or contact us on WhatsApp.")}$("ref").textContent=ref;$("success").classList.remove("hidden");e.target.reset();$("end_date").min=today;$("estimate").textContent="$0"});
function showError(id,msg){$(id).textContent=msg;$(id).classList.remove("hidden")}function clearError(id){$(id).textContent="";$(id).classList.add("hidden")}function closeSuccess(){$("success").classList.add("hidden")}
function showAdminLogin(){$("loginError").classList.add("hidden");$("adminLogin").classList.remove("hidden")}function hideAdminLogin(){$("adminLogin").classList.add("hidden")}
async function showAdmin(){const {data:{user}}=await supabaseClient.auth.getUser();if(user?.email?.toLowerCase()==="admin@caringshadeschildcare.com")return openAdmin();showAdminLogin()}
async function openAdmin(){hideAdminLogin();$("mainSite").classList.add("hidden");$("adminPanel").classList.remove("hidden");const {data:{user}}=await supabaseClient.auth.getUser();$("adminSignedIn").textContent=user?`Signed in as ${user.email}`:"";window.scrollTo(0,0);await refreshBookings()}
function hideAdmin(){$("adminPanel").classList.add("hidden");$("mainSite").classList.remove("hidden");window.scrollTo(0,0)}
$("loginForm").addEventListener("submit",async e=>{e.preventDefault();clearError("loginError");const email=$("adminEmail").value.trim(),password=$("adminPassword").value;const {data,error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)return showError("loginError","Invalid email or password. Please check your details and try again.");if(data.user?.email?.toLowerCase()!=="admin@caringshadeschildcare.com"){await supabaseClient.auth.signOut();return showError("loginError","This account is not authorised as the Caring Shades administrator.")}$("adminPassword").value="";await openAdmin()});
async function adminLogout(){await supabaseClient.auth.signOut();hideAdmin()}
async function refreshBookings(){$("bookingList").innerHTML="<div class='booking-item'><p>Loading bookings...</p></div>";const {data,error}=await supabaseClient.from("bookings").select("*").order("created_at",{ascending:false});if(error){console.error(error);$("bookingList").innerHTML="<div class='booking-item'><h3>Unable to load bookings</h3><p>Please refresh and make sure you are signed in as the Caring Shades administrator.</p></div>";return}renderAdmin(data||[])}
function renderAdmin(b){adminBookings=b;const now=new Date();$("total").textContent=b.length;$("pending").textContent=b.filter(x=>x.status==="Pending").length;$("confirmed").textContent=b.filter(x=>x.status==="Confirmed").length;$("upcoming").textContent=b.filter(x=>new Date((x.start_date||x.booking_date)+"T"+(x.start_time||"00:00"))>=now).length;$("bookingList").innerHTML=b.length?b.map((x,i)=>`<div class="booking-item"><div class="booking-top"><div><strong>${esc(x.booking_reference)}</strong><h3>${esc(x.parent_name)} — ${esc(x.service)}</h3><p>${esc(x.start_date||x.booking_date)}${x.end_date&&x.end_date!==x.start_date?` to ${esc(x.end_date)}`:""} ${esc(x.start_time||"")}${x.end_time?"–"+esc(x.end_time):""} · ${esc(x.number_of_children)} child(ren) · ${esc(x.location)}</p></div><span class="status">${esc(x.status)}</span></div><p><b>Phone:</b> ${esc(x.phone)} &nbsp; <b>Email:</b> ${esc(x.email)}<br><b>Ages:</b> ${esc(x.children_ages)} &nbsp; <b>Estimated:</b> ${money(x.estimated_price)}</p><p><b>Emergency:</b> ${esc(x.emergency_contact)}</p>${x.special_requirements?`<p><b>Special requirements:</b> ${esc(x.special_requirements)}</p>`:""}${x.notes?`<p><b>Notes:</b> ${esc(x.notes)}</p>`:""}<div class="booking-actions"><button onclick="setStatus('${esc(x.id)}','Confirmed')">Confirm</button><button onclick="setStatus('${esc(x.id)}','Declined')">Decline</button><button onclick="setStatus('${esc(x.id)}','Pending')">Set Pending</button><a class="btn small-btn" href="https://wa.me/${encodeURIComponent(String(x.phone||"").replace(/[^0-9]/g,''))}" target="_blank" rel="noopener">WhatsApp</a></div></div>`).join(""):"<div class='booking-item'><h3>No bookings yet</h3><p>New customer booking requests will appear here.</p></div>"}
async function setStatus(id,status){const {error}=await supabaseClient.from("bookings").update({status}).eq("id",id);if(error){alert("Could not update the booking. Please try again.");return}await refreshBookings()}
function exportBookings(){const cols=["booking_reference","parent_name","service","booking_date","start_date","end_date","start_time","end_time","number_of_children","children_ages","phone","email","emergency_contact","location","estimated_price","status","special_requirements","notes"];const rows=[cols,...adminBookings.map(x=>cols.map(c=>x[c]))];const csv=rows.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="caring-shades-bookings.csv";a.click();URL.revokeObjectURL(a.href)}
window.showAdmin=showAdmin;window.showAdminLogin=showAdminLogin;window.hideAdminLogin=hideAdminLogin;window.hideAdmin=hideAdmin;window.adminLogout=adminLogout;window.refreshBookings=refreshBookings;window.setStatus=setStatus;window.exportBookings=exportBookings;window.closeSuccess=closeSuccess;